### ISSUE TITLE
[UDP] Redirect der Ausgaben ins Log-File

### ISSUE THREAD

**Issue by simonsymhoven** [simonsymhoven/Datenkommunikation#24]
[UDP] Die Ausgaben der AuditLogServerGUI (ListView) sollen in ein LogFile geschrieben werden.

**Comment by simonsymhoven** [comment]
Logik umgesetzt, PR: #21

**Comment by simonsymhoven** [comment]
Review ausstehend.

**Comment by ottnorml** [comment]
Das Log-File kann nicht geschrieben werden.
```
java.nio.file.NoSuchFileException: <...>\DakoChatApplication\out\LogFiles\ChatAuditLog.dat
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:231)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.createFile(Files.java:647)
	at edu.hm.dako.chat.AuditLogServer.AuditLogUdpServer.writeDataToLogFile(AuditLogUdpServer.java:149)
	at edu.hm.dako.chat.AuditLogServer.AuditLogUdpServer$3.run(AuditLogUdpServer.java:134)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ottnorml** [comment]
@simonsymhoven Wieso hast das Log-File eig die Dateiendung `.dat` statt `.log`?

**Comment by simonsymhoven** [comment]
@ottnorml Das war so vorgegeben durch Prof. Mandl
